# Generated by Django 6.0.4 on 2026-07-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tenantorder',
            name='tenants_ten_tenant__80a493_idx',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='slug',
        ),
        migrations.AddField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='TenantOrder',
        ),
    ]
